name: Push-to-EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

  steps:
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v3
    with:
      node-version: ${{ matrix.node-version }}
      cache: 'npm'
  - run: npm ci
  - run: npm run build

  - name: Deploy to Server 1
    uses: easingthemes/ssh-deploy@main
    env:
      SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
      REMOTE_HOST: ${ { secrets.HOST_DNS }}
      REMOTE_USER: ${ { secrets.USERNAME }}
      TARGET: ${ { secrets.TARGET_DIR }}

  - name: Executing remote ssh commands using ssh key
    uses: appleboy/ssh-action@main
    with:
      host: ${{ secrets.HOST_DNS }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        sudo apt-get -y update
        sudo apt-get install -y apache2
        sudo systemctl start apache2
        sudo systemctl enable apache2
        cd home/build
        sudo mv * /var/www/html